# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Agent for AKS
  
steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1(f016713d-47fd-4917-a2c7-c2805377c59c)'
    subscriptionId: 'f016713d-47fd-4917-a2c7-c2805377c59c'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'AKSdatabase'
    location: 'East US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/SergeyTorotska/Task2/main/aksdb.json'
    deploymentMode: 'Incremental'